hub:
  image: selenium/hub
  ports:
    - "4444:4444"
  environment:
    - GRID_TIMEOUT=60
    - GRID_BROWSER_TIMEOUT=30
  restart: always

phantomjs:
  image: easypi/selenium-node-phantomjs
  ports:
    - "5555:5555"
  environment:
    - HOST=5.6.7.8
    - PORT=5555
    - HUB_HOST=1.2.3.4
    - HUB_PORT=4444
  restart: always
